# Generated by Django 5.2.4 on 2025-08-22 20:57

import django.db.models.deletion
import driver.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverloadinfo',
            name='load_secure_picture',
        ),
        migrations.RemoveField(
            model_name='driverloadinfo',
            name='pod',
        ),
        migrations.RemoveField(
            model_name='driverloadinfo',
            name='pulp_picture',
        ),
        migrations.RemoveField(
            model_name='driverloadinfo',
            name='reefer_picture',
        ),
        migrations.RemoveField(
            model_name='driverloadinfo',
            name='sealed_trailer_picture',
        ),
        migrations.RemoveField(
            model_name='driverloadinfo',
            name='trailer_picture',
        ),
        migrations.RemoveField(
            model_name='driverprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='driverloadinfo',
            name='order_number',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driverloadinfo',
            name='bol',
            field=models.FileField(upload_to=driver.models.bol_upload_to),
        ),
        migrations.CreateModel(
            name='DriverLoadPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_type', models.CharField(choices=[('trailer', 'Trailer'), ('reefer', 'Reefer'), ('pulp', 'Pulp'), ('loadsecure', 'Load Secure'), ('sealedtrailer', 'Sealed Trailer'), ('POD', 'POD')], max_length=50)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('image', models.ImageField(upload_to=driver.models.driver_photo_upload_to)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('load', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='driver.driverloadinfo')),
            ],
            options={
                'unique_together': {('load', 'photo_type', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='DriverLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.driverprofile')),
            ],
            options={
                'unique_together': {('driver',)},
            },
        ),
    ]
