# Generated by Django 5.2.4 on 2025-08-26 04:01

import driver.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_alter_driverloadphoto_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverloadinfo',
            name='pod',
            field=models.FileField(blank=True, null=True, upload_to=driver.models.pod_upload_to),
        ),
        migrations.AlterField(
            model_name='driverloadinfo',
            name='bol',
            field=models.FileField(blank=True, null=True, upload_to=driver.models.bol_upload_to),
        ),
    ]
