# Generated by Django 5.2.4 on 2025-08-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0007_driverloadinfo_seal_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverloadinfo',
            name='delivery_email_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='driverloadinfo',
            name='pickup_email_history',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='driverloadinfo',
            name='status',
            field=models.CharField(choices=[('pending_pickup', 'Pending Pickup'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('trip_completed', 'Trip Completed')], default='pending_pickup', max_length=20),
        ),
    ]
