# Generated by Django 5.2.4 on 2025-09-09 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0012_driverloadinfo_pulp_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverloadinfo',
            name='reefer_temp_bol',
            field=models.CharField(blank=True, help_text='Temperature mentioned on BOL', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='driverloadinfo',
            name='reefer_temp_shipper',
            field=models.CharField(blank=True, help_text='Temperature set by shipper', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='driverloadinfo',
            name='reefer_temp_unit',
            field=models.CharField(choices=[('C', 'Celsius'), ('F', 'Fahrenheit')], default='C', help_text='Temperature unit', max_length=2),
        ),
    ]
