# Generated by Django 5.2.4 on 2025-09-14 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0013_driverloadinfo_reefer_temp_bol_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApprovedDriver',
        ),
        migrations.AddField(
            model_name='company',
            name='scac_code',
            field=models.CharField(db_index=True, default='HHTP', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverprofile',
            name='scac_code',
            field=models.CharField(default='HHTP', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driverloadinfo',
            name='status',
            field=models.CharField(choices=[('pending_pickup', 'Pending Pickup'), ('in_transit', 'In Transit'), ('pickup_completed', 'Pickup Completed'), ('delivered', 'Delivered')], default='pending_pickup', max_length=20),
        ),
    ]
