# Generated by Django 5.2.4 on 2025-09-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0014_delete_approveddriver_company_scac_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='scac_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='driverprofile',
            name='scac_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
