# Generated by Django 5.2.4 on 2025-09-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0015_alter_company_scac_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverloadinfo',
            name='equipment_type',
            field=models.CharField(choices=[('dry_van', 'Dry Van'), ('reefer', 'Reefer'), ('flatbed', 'Flatbed'), ('stepdeck', 'Stepdeck'), ('heated_van', 'Heated Van'), ('straight_truck', 'Straight Truck')], default='dry_van', help_text='Type of equipment used', max_length=20),
        ),
    ]
