"""
Django settings for backend project.
Generated by 'django-admin startproject' using Django 5.2.4.
"""

from pathlib import Path
#from celery.schedules import crontab
import os

# ----------------------------
# Base directory
# ----------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ----------------------------
# Security
# ----------------------------
SECRET_KEY = 'django-insecure-$j056hcp9i!94ebl_v=vf%p_fkjyxltibcmi16z2+(6&tz^!6a'
DEBUG = False
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '10.0.2.2','mobile-app-gpehf7f5c4h9cre6.canadacentral-01.azurewebsites.net']  # Android emulator

CSRF_TRUSTED_ORIGINS = [
    "https://mobile-app-gpehf7f5c4h9cre6.canadacentral-01.azurewebsites.net"
]

# ----------------------------
# Applications
# ----------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'driver',
    'corsheaders',
    'import_export',
    'storages',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# ----------------------------
# Database
# ----------------------------
import dj_database_url

DATABASES = {
    'default': dj_database_url.config(default=os.getenv('DATABASE_URL'))
}


# ----------------------------
# Password validation
# ----------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ----------------------------
# Internationalization
# ----------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/Toronto'  # Local timezone
USE_I18N = True
USE_L10N = True
USE_TZ = True

# ----------------------------
# Static & Media
# ----------------------------
STATIC_URL = 'static/'

# ----------------------------
# Azure Storage
# ----------------------------
AZURE_ACCOUNT_NAME = os.getenv('AZURE_ACCOUNT_NAME')
AZURE_ACCOUNT_KEY = os.getenv('AZURE_ACCOUNT_KEY')
AZURE_CONTAINER = os.getenv('AZURE_CONTAINER', 'media')
AZURE_URL_EXPIRATION_SECS = None

DEFAULT_FILE_STORAGE = 'backend.azure_storage.AzureMediaStorage'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
MEDIA_URL = f"https://{AZURE_ACCOUNT_NAME}.blob.core.windows.net/{AZURE_CONTAINER}/"


# ----------------------------
# CORS
# ----------------------------
CORS_ALLOW_ALL_ORIGINS = True

# ----------------------------
# Email (Azure SMTP)
# ----------------------------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.office365.com')  # Azure / Microsoft 365 SMTP
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')  # Your Azure email address
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')  # Your Azure app password or email password
DEFAULT_FROM_EMAIL = f"H&H Support <{os.getenv('EMAIL_HOST_USER')}>"


# ----------------------------
# Celery
# ----------------------------
# CELERY_BROKER_URL = 'redis://localhost:6379/0'
# CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
#CELERY_TIMEZONE = 'America/Toronto'
# CELERY_ENABLE_UTC = False

#CELERY_BEAT_SCHEDULE = {
#    'notify-drivers-twice-daily': {
#        'task': 'driver.tasks.notify_drivers_in_transit',
#        'schedule': crontab(minute=0, hour='10,18'),  # 10 AM & 6 PM local time
 #   },
#}

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

AZURE_MAPS_KEY = os.environ.get("AZURE_MAPS_KEY")


# ----------------------------
# Celery (Azure Redis SSL)
# ----------------------------
import ssl

REDIS_HOST = os.getenv("REDIS_HOST")
REDIS_PORT = os.getenv("REDIS_PORT", "6380")  # Azure Redis SSL port
REDIS_PASSWORD = os.getenv("REDIS_PASSWORD")

# Azure Redis uses SSL — build the secure URL dynamically
CELERY_BROKER_URL = f"rediss://:{REDIS_PASSWORD}@{REDIS_HOST}:{REDIS_PORT}/0"
CELERY_RESULT_BACKEND = CELERY_BROKER_URL

# Required for SSL connections on Azure Redis
BROKER_USE_SSL = {"ssl_cert_reqs": ssl.CERT_NONE}
CELERY_BROKER_USE_SSL = BROKER_USE_SSL
CELERY_REDIS_BACKEND_USE_SSL = {"ssl_cert_reqs": ssl.CERT_NONE}
CELERY_RESULT_BACKEND_USE_SSL = CELERY_REDIS_BACKEND_USE_SSL

# Optional – timezone consistency
CELERY_TIMEZONE = "America/Toronto"
CELERY_ENABLE_UTC = False




