# Generated by Django 5.2.4 on 2025-08-21 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_index=True, max_length=100)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('driver_name', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='driver.company')),
            ],
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('company', models.CharField(db_index=True, max_length=100)),
                ('license_number', models.CharField(default='UNKNOWN', max_length=50, unique=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DriverLoadInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.CharField(max_length=50)),
                ('trailer_number', models.CharField(max_length=50)),
                ('customer_name', models.CharField(db_index=True, max_length=100)),
                ('load_number', models.CharField(max_length=100)),
                ('pickup_number', models.CharField(max_length=100)),
                ('trailer_picture', models.ImageField(upload_to='driver_uploads/trailer/')),
                ('reefer_pre_cool', models.CharField(max_length=50)),
                ('pulp_picture', models.ImageField(upload_to='driver_uploads/pulp/')),
                ('reefer_picture', models.ImageField(upload_to='driver_uploads/reefer/')),
                ('load_secure_picture', models.ImageField(upload_to='driver_uploads/load_secure/')),
                ('sealed_trailer_picture', models.ImageField(upload_to='driver_uploads/sealed_trailer/')),
                ('bol', models.FileField(upload_to='driver_uploads/bol/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('delivery_number', models.CharField(blank=True, max_length=100, null=True)),
                ('pod', models.FileField(blank=True, null=True, upload_to='driver_uploads/pod/')),
                ('pickup_datetime', models.DateTimeField(blank=True, null=True)),
                ('delivery_datetime', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads', to='driver.driverprofile')),
            ],
        ),
    ]
