# Generated by Django 5.2.4 on 2025-08-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_remove_driverloadinfo_load_secure_picture_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='driverlocation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='company_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driverlocation',
            name='license_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='driverlocation',
            unique_together={('license_number', 'company_name')},
        ),
    ]
