# Generated by Django 5.2.4 on 2025-08-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_driverloadinfo_pod_alter_driverloadinfo_bol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverloadphoto',
            name='photo_type',
            field=models.CharField(choices=[('trailer', 'Trailer'), ('reefer', 'Reefer'), ('pulp', 'Pulp'), ('load_secure', 'Load Secure'), ('sealed_trailer', 'Sealed Trailer'), ('POD', 'POD'), ('bol', 'BOL')], max_length=50),
        ),
    ]
