# Generated by Django 5.2.4 on 2025-08-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0008_driverloadinfo_delivery_email_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverloadinfo',
            name='last_notification_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverloadinfo',
            name='status',
            field=models.CharField(choices=[('pending_pickup', 'Pending Pickup'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='pending_pickup', max_length=20),
        ),
    ]
