# Generated by Django 5.2.4 on 2025-08-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0009_driverloadinfo_last_notification_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverprofile',
            name='device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
