# Generated by Django 5.2.4 on 2025-08-30 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0010_driverprofile_device_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverloadinfo',
            old_name='notes',
            new_name='delivery_notes',
        ),
        migrations.AddField(
            model_name='driverloadinfo',
            name='pickup_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
