# Generated by Django 5.2.4 on 2025-09-03 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0011_rename_notes_driverloadinfo_delivery_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverloadinfo',
            name='pulp_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
